name: riverpod_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_riverpod: ^2.1.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  oxidized: ^5.2.0
  riverpod_annotation: ^1.0.6
  auto_route: ^5.0.2
  salomon_bottom_bar: ^3.3.1
  freezed_annotation: ^2.2.0
  firebase_core: ^2.3.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  riverpod_generator: ^1.0.6
  auto_route_generator: ^5.0.3
flutter:

  uses-material-design: true
